name: dk-java
namespace: ""
cdPipelineName: ""
cdPipelineStageName: ""
dnsWildcard: eks-delivery.aws.main.edp.projects.epam.com

database:
  required: false


ingress:
  required: false

image:
  name: dk-java
  version: latest